### ISSUE TITLE
Error while installing library

### ISSUE THREAD

**Issue by keyur9** [TheDevFromKer/Fake-Headers#1]
Hey there! thanks for the great library. Was trying to install it but ran into error - `with open('README.MD', 'r') as f:
    IOError: [Errno 2] No such file or directory: 'README.MD'`. 

It seems the `setup.py` file need to be updated as it couldn't find `README.MD`, should it be `README.md`?

Thanks,

**Comment by TheDevFromKer** [comment]
Yep, thanks @keyur9 !
